# fc_dropout: !!float 0.05
# head_dropout: !!float 0.0
# patch_len: !!int 16
# stride: !!int 8
# padding_patch: !!str end
# revin: !!int 0
# affine: !!int 0
# subtract_last: !!int 0
# decomposition: !!int 0
# kernel_size: !!int 25
# tcn_output_dim: !!int 320
# tcn_layer: !!int 2
# tcn_hidden: !!int 160
# individual: !!int 1
# channel_cross: !!bool false
model: iTransformer
individual: False
# mha_type: "org"
# gamma: 0.9
res_attention: true
# norm: "batchnorm"
# affine: false
ff_type: "org"
nh: 64
fc_dropout: 0
dropout: 0

n_heads: 8
e_layers: 
  electricity: 3
  ETTh2: 2
  ETTh1: 2
  ETTm1: 2
  ETTm2: 2
  WTH: 3
  weather: 3
  exchange: 2
  traffic: 4
  nyctaxi: 3
  PEMS04: 3
  PEMS03: 3
  PEMS07: 3
  PEMS08: 3
  solar: 3

d_model:
  electricity: 512
  ETTh2: 128
  ETTh1: 128
  ETTm1: 128
  ETTm2: 128
  WTH: 512
  weather: 512
  exchange: 128
  traffic: 512
  nyctaxi: 256
  PEMS04: 512
  PEMS03: 512
  PEMS07: 512
  PEMS08: 512
  solar: 256

d_ff:
  electricity: 512
  ETTh2: 128
  ETTh1: 128
  ETTm1: 128
  ETTm2: 128
  WTH: 512
  weather: 512
  exchange: 128
  traffic: 512
  nyctaxi: 256
  PEMS04: 512
  PEMS03: 512
  PEMS07: 512
  PEMS08: 512
  solar: 256
embed: "timeF"
use_norm: true
partial_start_index: 0
inverse: false
class_strategy: "projection"
factor: 1
activation: "gelu"
output_attention: false
